### ISSUE TITLE
Error when doing the Getting Started

### ISSUE THREAD

**Issue by curquiza** [watzon/octokit.cr#6]
In `test.cr`:

```crystal
require "octokit"

# Create a new Octokit Client
github = Octokit.client("curquiza", "password")

# Fetch information about the logged in user
pp github.user

# Fetch information about another user
pp github.user("asterite")

puts "Hello"
```

`shards.yml`:
```yml
name: crystal-test
version: 0.1.0

authors:
  - your-name-here <your-email-here>

targets:
  crystal-test:
    main: src/crystal-test.cr

dependencies:
  octokit:
    github: watzon/octokit.cr

crystal: 0.35.1

license: MIT
```

Run `crystal run test.cr`:
```bash
$ crystal run src/crystal-test.cr
In /usr/local/Cellar/crystal/0.35.1_1/src/logger.cr:124:3

 124 | def initialize(@io : IO?, @level = Severity::INFO, @formatter = DEFAULT_FORMATTER, @progname = "")
       ^---------
Warning: Deprecated Logger#initialize. Use `Log` module instead

A total of 1 warnings were found.
Fetching repositories
Unhandled exception: Missing hash key: HTTP::Headers::Key(@name="X-GitHub-OTP") (KeyError)
  from ../../../../../usr/local/Cellar/crystal/0.35.1_1/src/hash.cr:1030:9 in '[]'
  from ../../../../../usr/local/Cellar/crystal/0.35.1_1/src/http/headers.cr:71:5 in '[]'
  from lib/octokit/src/octokit/error.cr:202:34 in 'required_header'
  from lib/octokit/src/octokit/error.cr:54:10 in 'error_for_401'
  from lib/octokit/src/octokit/error.cr:19:37 in 'from_response'
  from lib/octokit/src/octokit/connection.cr:160:9 in 'handle_error'
  from lib/octokit/src/octokit/connection.cr:137:7 in 'request'
  from lib/octokit/src/octokit/connection.cr:268:18 in 'fetch_page'
  from lib/octokit/src/octokit/connection.cr:289:9 in 'fetch_next'
  from lib/octokit/src/octokit/connection.cr:245:11 in 'fetch_all'
  from lib/octokit/src/octokit.cr:53:9 in '__crystal_main'
  from ../../../../../usr/local/Cellar/crystal/0.35.1_1/src/crystal/main.cr:105:5 in 'main_user_code'
  from ../../../../../usr/local/Cellar/crystal/0.35.1_1/src/crystal/main.cr:91:7 in 'main'
  from ../../../../../usr/local/Cellar/crystal/0.35.1_1/src/crystal/main.cr:114:3 in 'main'
```
